[workspace]
authors = ["Mridul Seth <git@mriduls.com>"]
channels = ["conda-forge"]
name = "visa-pixi-locks"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "2025.8.2"

[tasks]

# The base deps used by all envs.
[dependencies]
python = ">=3.12,<3.13"
ipywidgets = ">=8.1.5,<9"
ipympl = ">=0.9.7,<0.10"
pythreejs = ">=2.4.2,<3"
jupyterlab-h5web = ">=12.4.0,<13"
ipykernel = ">=6.29.5,<7"
scitacean = ">=25.3.2,<26"
pooch = "==1.8.2"

[feature.convert]
dependencies = { python = ">=3.12", pip = "*" }
pypi-dependencies = { pixi-to-conda-lock = "*"}
tasks = { convert = "pixi-to-conda-lock" }

[feature.base.dependencies]
jupyterlab = "*"
nb_conda_kernels = "*"

[feature.reflectometry.dependencies]
essreflectometry = "==25.05.1"

[feature.diffraction.dependencies]
essdiffraction = "==25.06.0"

[feature.sans.dependencies]
esssans = "==25.06.0"
esspolarization = "==25.07.0"

[feature.imaging.dependencies]
essimaging = "==25.04.0"

[feature.nmx.dependencies]
essnmx = "==25.03.0"
scippneutron = "==25.07.0"

[feature.mcstas]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[feature.mcstas.dependencies]
mcstas = "==3.5.32"
mcxtrace = "==3.5.32"
xraylib = "*"
ncrystal = "*"
mcpl = "*"
nexus = "*"
openmpi = "*"

[feature.cil]
platforms = ["linux-64"]
channels = ["conda-forge", "ccpi", "https://software.repos.intel.com/python/conda"]

[feature.cil.dependencies]
cil = "==24.3.0"
ipp = "==2021.12"
astra-toolbox = "*"
tigre = "*"
ccpi-regulariser = "*"
tomophantom = "*"
scikit-image = "*"

[feature.dmsc_ss.dependencies]
mcstas  = "*"
scitacean  = "*"
paramiko = "*"
scipy = "*"
scippnexus = "*"
scippneutron = "*"
scipp = "*"
pooch = "*"
plopp = "*"
pandas = "*"
numpy = "*"
mpltoolbox = "*"
matplotlib = "*"
h5py = "*"
python-graphviz = "*"
easyscience = "*"
dynesty = "*"
corner = "*"
emcee = "*"
easydiffraction = "*"
darkdetect = "*"
plotly = "<6.0.0"
py3dmol = "*"

[feature.dmsc_ss.pypi-dependencies]
mcstastox = "*"

[environments]
base = ["base"]
ess-reflectometry = ["reflectometry"]
ess-diffraction = ["diffraction"]
ess-sans = ["sans"]
ess-nmx = ["nmx"]
ess-mcstas = ["mcstas"]
ess-cil = ["cil"]
ess-imaging = ["imaging"]
dmsc-summer-school = ["dmsc_ss"]
convert = {features = ["convert"], no-default-feature = true}
